### PR TITLE
Fix search from showing sections with no results 

### LINKED ISSUE #408: Don't show boilerplates/snippets/featured projects if there are no results
Or say "no results found"

image

image alt: screenshot of https://developers.cloudflare.com/workers/templates/?q=rust

### PR DESCRIPTION
**Pull request by victoriabernard92**
Before:

After:

fixes #408

### CODE REVIEW

File: static/js/templates.js [hunk 1]
```diff
@@ -52,8 +54,19 @@ const processSearch = () => {
...
+      }`),
   )
+  // Remove section headers that contain no results
+  const sectionHeaders = document.querySelectorAll('#results>h2')
+  sectionHeaders.forEach(header => {
+    // all headers' next sibling is a `section` that parents the templates
+    let matches = [...header.nextElementSibling.childNodes].filter(el =>
+      results.find(result => result.id === el.id),
+    )
+    if (!matches.length) header.style.display = 'none'
```
Comment (signalnerve) [inline static/js/templates.js]: Does this re-add the header if a result is found in that category, after it's been hidden the first time?
